### ISSUE TITLE
Not working in servers

### ISSUE THREAD

**Issue by Baardiel** [cmooref17/Lethal-Company-ReservedItemSlotMods#50]
I have a modded sv with friends and they don't see the slots. We have installed just the Flashlight n Walkie + the core mod.
We used to have the key n weapons one installed and it worked just the first time we opened the sv, then the slots  just disappeared for them, everytime they pickup something that should've gone to the slots it bugs them and they need to restart

**Comment by BigChefMan07** [comment]
I had the same issue yesterday and have figured out the issue.
 **### Make sure you do NOT have any copies or modified versions of the reserved slots**, as i accidentally downloaded ReservedFlashPlus while already having ReservedFlashlight.

**Comment by cmooref17** [comment]
Sorry. This is an old issue I never looked into. I'm going to close it. Feel free to create a new ticket for any other issues.
